theme: jekyll-theme-minimal
title: 汪宗成的小站
description: 

邮箱：2021103675@ruc.edu.cn

[知乎](https://www.zhihu.com/people/dong-zhi-qing-lie)

[github](https://github.com/wangzongcheng1222)

[豆瓣](https://www.douban.com/people/231742715)

[网易云音乐](https://music.163.com/#/user/home?id=4874054347)




