theme: jekyll-theme-minimal
title: Sonic Youth!
description: >
    学习记录主页
    <br></br>
    联系方式：
    <br></br>
    微信: Solswzc &nbsp QQ: 1277145165
    <br></br>
    <a href="https://www.zhihu.com/people/dong-zhi-qing-lie">知乎&nbsp;</a>
    <a href="https://music.163.com/#/user/home?id=4874054347">网易云音乐&nbsp;</a>
    <a href="https://www.douban.com/people/231742715">豆瓣&nbsp;</a>
    <a href="https://space.bilibili.com/1737715113">bilibili&nbsp;</a>
    <a href="https://github.com/wangzongcheng1222">GitHub&nbsp;</a>
github:
    is\_project\_page:false








