theme: jekyll-theme-minimal
title: Sonic Youth!
description: > <br></br>
<a href="https://www.zhihu.com/people/dong-zhi-qing-lie">知乎</a>
<a href="https://github.com/wangzongcheng1222">GitHub</a>
<a href="https://www.douban.com/people/231742715">豆瓣</a>
<a href="https://music.163.com/#/user/home?id=4874054347">网易云音乐</a>
<a href="https://space.bilibili.com/1737715113">bilibili</a>








