theme: jekyll-theme-minimal
title: Sonic Youth!
>
记录学习
<br><\br>
<a href="https://www.zhihu.com/people/dong-zhi-qing-lie">B乎</a>
<a href="https://github.com/wangzongcheng1222">gayhub</a>
<a href="https://www.douban.com/people/231742715">豆瓣</a>
<a href="https://music.163.com/#/user/home?id=4874054347">网抑云</a>







